name: publish-master

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u christopherarter -p ${{ secrets.DOCKER_PASSWORD }} registry.hub.docker.com/christopherarter/laravel
      - run: docker build -t registry.hub.docker.com/christopherarter/laravel:latest . --file Dockerfile
      - run: docker push registry.hub.docker.com/christopherarter/laravel